import { createFileRoute } from '@tanstack/react-router';
import { LegalPage, type LegalSection } from '@/components/legal-page';
import { pageHead } from '@/lib/site';
export const Route = createFileRoute('/privacy')({ head: () => pageHead('Privacy Policy', 'How Ttyl BestAI collects, uses, retains and protects application information, SMS opt-in data and AI conversations.'), component: PrivacyPage });
const sections: LegalSection[] = [
 { title: 'Who we are', content: <><p>Ttyl BestAI is the service and Brand name for our private AI texting companion. This Privacy Policy explains how information is handled when you visit our website, apply for access, or use the companion service after it becomes available.</p><p>Operator/legal entity: <span className="placeholder">[Legal entity name — to be provided]</span>. Privacy contact: <span className="placeholder">[Privacy contact email — to be provided]</span>. These are placeholders, not active contact details.</p><p>The website currently accepts applications only. It does not send SMS messages or activate companion conversations.</p></> },
 { title: 'Information we collect', content: <><p>Depending on how you interact with Ttyl BestAI, we collect:</p><ul><li><strong>Contact information:</strong> your name, email address and phone number.</li><li><strong>Application information:</strong> what you want from an AI texting companion, how you heard about us, optional details you share, and your acknowledgement that applying is not SMS consent.</li><li><strong>SMS and conversation information, when activated:</strong> message content, conversation history, timestamps, delivery information, enrollment confirmations, HELP requests and STOP requests.</li><li><strong>Technical information:</strong> information needed to deliver and secure the website and service, such as IP addresses, browser and device details, request logs and error information.</li><li><strong>Service communications:</strong> support requests, feedback and information necessary to manage access.</li></ul><p>Please avoid sharing passwords, financial credentials, medical records or other highly sensitive information in applications or conversations.</p></> },
 { title: 'How we use information', content: <><p>We use information to review access applications, communicate approval decisions and activation instructions, operate the service, generate AI responses, maintain relevant conversation context, provide support, handle opt-in and opt-out requests, prevent misuse, troubleshoot problems and meet applicable obligations.</p><p>An application is a request for access only. Application approval does not enroll you in SMS messaging. Recurring SMS access requires a separate affirmative opt-in.</p><p>Where applicable law requires a legal basis, we process information using the basis appropriate to the activity, such as providing a requested service, consent where required, legitimate operational interests, or legal obligations.</p></> },
 { title: 'Technology providers and sharing', content: <><p>Conversations may be processed by third-party technology providers necessary to operate the AI service. These may include AI model providers, hosting and database providers, communications providers and service support providers. They receive information needed for their role in operating the service.</p><p><strong>We do not sell or share your SMS opt-in data or personal information with third parties for marketing purposes.</strong></p><p>Information may also be disclosed when necessary to comply with applicable law, respond to valid legal requests, protect rights or safety, or in connection with a business transfer subject to appropriate protections. We do not promise that every provider’s systems or practices are identical to ours.</p></> },
 { title: 'Retention and deletion', content: <><p>We retain application information only as needed to review requests, manage access and resolve related questions. If the SMS service is activated, conversation history and operational records may be retained as needed to provide the service, maintain continuity, handle support or comply with applicable requirements.</p><p>Retention depends on the purpose, the sensitivity of the information and applicable obligations. Opt-out records may be retained to honor your decision not to receive messages. Deletion may be delayed for security, legal obligations or routine backup cycles.</p><p>You may request deletion through the privacy contact once it is provided. We will assess requests under applicable law and explain any necessary exceptions.</p></> },
 { title: 'Security and confidentiality', content: <><p>We use reasonable technical and organizational safeguards designed to protect information against unauthorized access, disclosure, alteration and loss, including restricting access to application information.</p><p>No website, transmission method, SMS channel or storage system is completely secure. SMS is not a confidential or end-to-end encrypted channel, and messages may be accessible through your device, carrier or messaging backups. Do not send information you would not want transmitted over SMS.</p><p>“Private access” describes the approval-based service, not a guarantee of absolute confidentiality or a promise that no technology provider processes messages.</p></> },
 { title: 'Your choices and rights', content: <><p>You may choose not to apply, omit optional application details, decline SMS activation, or cancel SMS messages by replying STOP. Reply HELP for messaging help when the SMS service is active. Withdrawing SMS consent does not automatically delete previously stored records.</p><p>Depending on where you live, you may have rights to request access, correction, deletion, portability or restrictions on processing, or to object to certain processing and withdraw consent. We may verify your identity before responding. You may also be entitled to contact your local privacy regulator.</p></> },
 { title: 'Cookies, international processing and age', content: <><p>The website may use essential technologies needed for operation and security. Optional tracking or advertising technologies are not part of the current application flow. Browser settings can restrict cookies, although this may affect some website functions.</p><p>Technology providers may process information in countries other than your own. Where required, appropriate measures must be used for international transfers. Access is subject to the eligibility requirements in our Terms &amp; Conditions; users must be legally able to consent to the service. We do not knowingly seek information from children who cannot lawfully consent.</p></> },
 { title: 'Updates and contact', content: <><p>We may update this policy as the service changes. The date at the top identifies the latest version. Material changes will be communicated as appropriate.</p><p>For privacy questions or requests, contact Ttyl BestAI at <span className="placeholder">[Privacy contact email — to be provided]</span>.</p><p>Mailing address, if applicable: <span className="placeholder">[Mailing address — to be provided]</span>. Contact details and operating practices must be finalized before the SMS service launches.</p></> },
];
function PrivacyPage() { return <LegalPage title="Privacy Policy" intro="Your information deserves a clear explanation. Here’s what we collect, why we use it, and the choices you have." sections={sections} />; }
