import { createFileRoute } from '@tanstack/react-router';
import { LegalPage, type LegalSection } from '@/components/legal-page';
import { pageHead } from '@/lib/site';
export const Route = createFileRoute('/terms')({ head: () => pageHead('Terms & Conditions', 'Review Ttyl BestAI eligibility, acceptable use, AI limitations and SMS Terms, including affirmative opt-in and STOP instructions.'), component: TermsPage });
const sections: LegalSection[] = [
 { title: 'About these terms', content: <><p>These Terms &amp; Conditions govern your use of the Ttyl BestAI website and, when activated, its AI texting companion service. Ttyl BestAI is the service and Brand name. By using the service, you agree to these terms to the extent permitted by applicable law.</p><p>Contact: <span className="placeholder">[Support contact email — to be provided]</span>.</p><p>The website currently provides information and accepts applications. It does not send SMS or activate SMS conversations.</p></> },
 { title: 'Eligibility and access approval', content: <><p>You must be legally able to agree to these terms and consent to the service in your location. You must provide accurate application and contact information and have permission to use the phone number you provide.</p><p>Access is approval-based. Submitting an application does not guarantee approval, availability, enrollment or a response within a particular time. We may approve, decline, restrict or revoke access based on service availability, suitability and compliance with these terms.</p><p>Approval does not constitute SMS consent. Approved users receive separate SMS activation instructions and must affirmatively opt in.</p></> },
 { title: 'SMS Terms', content: <><p>SMS access requires affirmative opt-in. Application approval does not itself constitute SMS consent.</p><ul><li>Only approved users may activate SMS access.</li><li>Text JOIN to the Ttyl BestAI phone number supplied in your activation instructions, read the welcome/disclosure message, then reply Y to confirm enrollment.</li><li>Message frequency varies based on your conversations.</li><li><strong>Message and data rates may apply.</strong> Your carrier’s rates and plan terms apply.</li><li>Reply HELP for help.</li><li>Reply STOP to cancel. After opting out, you may receive a confirmation of your cancellation; recurring conversational messages will stop.</li></ul><p>SMS delivery may be delayed or unavailable due to carrier, device or technical conditions. Neither Ttyl BestAI nor carriers guarantee delivery. Notify us through the support contact if your phone number changes or is reassigned.</p><p>Support contact: <span className="placeholder">[Support contact email — to be provided]</span>. Do not attempt enrollment until you have received valid activation instructions.</p></> },
 { title: 'Acceptable use', content: <><p>Use the service lawfully and respectfully. Do not use it to harass, threaten or exploit others; facilitate illegal activity; distribute malicious content; impersonate someone; infringe intellectual property or privacy rights; or attempt unauthorized access, automated abuse or disruption.</p><p>Do not share another person’s private information without permission. Keep access and device credentials secure. You are responsible for the content you send and for evaluating the responses you receive.</p></> },
 { title: 'AI-generated content', content: <><p>Ttyl BestAI is an AI companion, not a human. Responses are automatically generated and can be inaccurate, incomplete, inappropriate or inconsistent. Similar responses may be generated for other users.</p><p>Use your own judgment and independently verify important information. The service does not promise to understand every message, remember every detail or provide particular outcomes. Do not rely on generated content as professional advice.</p></> },
 { title: 'Service limitations', content: <><p>The service is for general conversation and exploring everyday thoughts and ideas. It does not provide medical care, therapy, professional counseling, legal or financial advice, emergency assistance or crisis support.</p><p>The service is not monitored for emergencies and is not an emergency contact. Contact appropriate local emergency services if immediate assistance is needed.</p><p>Availability, response timing, conversation context and supported capabilities may vary. SMS is not an end-to-end encrypted communication channel.</p></> },
 { title: 'Intellectual property and your content', content: <><p>Ttyl BestAI’s branding, website design, software and other original service materials belong to their respective owners. These terms do not transfer ownership of those materials. You may use the service for its intended purpose but may not copy or exploit protected materials without permission or another lawful basis.</p><p>You retain any rights you have in content you submit. You give us permission to process that content as necessary to operate and support the service, including through technology providers described in our Privacy Policy. No exclusive ownership or copyright protection of AI-generated responses is guaranteed.</p></> },
 { title: 'Suspension and termination', content: <><p>You can stop using the service at any time and cancel SMS messaging by replying STOP. We may suspend or terminate access for violations, misuse, security concerns, legal requirements or changes in service availability.</p><p>Termination does not automatically delete all stored information. Retention and deletion are addressed in our Privacy Policy. Provisions that reasonably need to continue after termination remain applicable to the extent permitted by law.</p></> },
 { title: 'Disclaimers and responsibility', content: <><p>To the extent permitted by applicable law, the service is provided “as is” and “as available,” without guarantees of accuracy, uninterrupted operation, fitness for a particular purpose or specific results.</p><p>We are not responsible for decisions you make based on AI-generated content or for carrier and device limitations, except where responsibility cannot lawfully be excluded. Nothing in these terms excludes liability or statutory rights that applicable law does not permit us to exclude.</p><p>We do not impose an invented monetary liability cap or specify a governing jurisdiction before operator details are finalized.</p></> },
 { title: 'Changes and contact', content: <><p>We may change, pause or discontinue features and update these terms as the service evolves. The latest revision date appears at the top of this page. We will provide notice of material changes where appropriate or required. If you do not agree to updated terms, stop using the service.</p><p>Questions about Ttyl BestAI or these terms: <span className="placeholder">[Support contact email — to be provided]</span>.</p></> },
];
function TermsPage() { return <LegalPage title="Terms & Conditions" intro="Clear expectations for a thoughtful conversation. Please read these terms before using Ttyl BestAI." sections={sections} />; }
